DROP TABLE EMPLOYEE;

CREATE TABLE EMPLOYEE(
    EMP_NO NUMBER(3) NOT NULL UNIQUE,
    EMP_NAME VARCHAR(30) NOT NULL,
    EMP_SAL NUMBER(8,2) NOT NULL,
    EMP_COMM NUMBER(6,1) NOT NULL,
    DEPT_NO NUMBER(3) NOT NULL
);

ALTER TABLE EMPLOYEE DROP COLUMN EMP_COMM;
ALTER TABLE EMPLOYEE ADD EMP_COMM NUMBER(6,1);

ALTER TABLE EMPLOYEE DROP COLUMN DEPT_NO;
ALTER TABLE EMPLOYEE ADD DEPT_NO NUMBER(3);
INSERT INTO EMPLOYEE(EMP_NO,EMP_NAME,EMP_SAL,EMP_COMM,DEPT_NO) VALUES('101','Smith','800','455','20');
INSERT INTO EMPLOYEE(EMP_NO,EMP_NAME,EMP_SAL,EMP_COMM,DEPT_NO) VALUES('102','Snehal','1600','0','25');
INSERT INTO EMPLOYEE(EMP_NO,EMP_NAME,EMP_SAL,EMP_COMM,DEPT_NO) VALUES('103','Adama','1100','425','20');
INSERT INTO EMPLOYEE(EMP_NO,EMP_NAME,EMP_SAL,EMP_COMM,DEPT_NO) VALUES('104','Aman','3000','','15');
INSERT INTO EMPLOYEE(EMP_NO,EMP_NAME,EMP_SAL,EMP_COMM,DEPT_NO) VALUES('105','Anita','5000','50000','10');
INSERT INTO EMPLOYEE(EMP_NO,EMP_NAME,EMP_SAL,EMP_COMM,DEPT_NO) VALUES('106','Anamika','2975','','30');
SELECT * FROM EMPLOYEE;

DROP TABLE JOB;

CREATE TABLE JOB(
    JOB_ID VARCHAR(15) NOT NULL UNIQUE,
    JOB_TITLE VARCHAR(30) NOT NULL,
    MIN_SAL NUMBER(7,2) NOT NULL,
    MAX_SAL NUMBER(7,2) NOT NULL
);

INSERT INTO JOB(JOB_ID,JOB_TITLE,MIN_SAL,MAX_SAL) VALUES('IT PROG','Programmer','4000','10000');
INSERT INTO JOB(JOB_ID,JOB_TITLE,MIN_SAL,MAX_SAL) VALUES('MK MGR','Marketing Manager','9000','15000');
INSERT INTO JOB(JOB_ID,JOB_TITLE,MIN_SAL,MAX_SAL) VALUES('FI MGR','Finance Manager','8200','12000');
INSERT INTO JOB(JOB_ID,JOB_TITLE,MIN_SAL,MAX_SAL) VALUES('FI ACC','Account','4200','9000');
INSERT INTO JOB(JOB_ID,JOB_TITLE,MIN_SAL,MAX_SAL) VALUES('LEC','Lecturer','6000','17000');
INSERT INTO JOB(JOB_ID,JOB_TITLE,MIN_SAL,MAX_SAL) VALUES('COMP OP','Computer Operator','1500','13000');

SELECT * FROM JOB;


DROP TABLE DEPOSIT;

CREATE TABLE DEPOSIT(
    A_NO VARCHAR(5) NOT NULL UNIQUE,
    CNAME VARCHAR(15) NOT NULL,
    BNAME VARCHAR(10),
    AMOUNT NUMBER(7,2) NOT NULL,
    A_DATE DATE NOT NULL
);

INSERT INTO DEPOSIT(A_NO,CNAME,BNAME,AMOUNT,A_DATE) VALUES('101','Anil','andheri','7000','01-jan-06');
INSERT INTO DEPOSIT(A_NO,CNAME,BNAME,AMOUNT,A_DATE) VALUES('102','sunil','virar','5000','15-jul-06');
INSERT INTO DEPOSIT(A_NO,CNAME,BNAME,AMOUNT,A_DATE) VALUES('103','jay','villeparle','6500','12-mar-06');
INSERT INTO DEPOSIT(A_NO,CNAME,BNAME,AMOUNT,A_DATE) VALUES('104','vijay','andheri','8000','17-sep-06');
INSERT INTO DEPOSIT(A_NO,CNAME,BNAME,AMOUNT,A_DATE) VALUES('105','keyur','dadar','7500','19-nov-06');
INSERT INTO DEPOSIT(A_NO,CNAME,BNAME,AMOUNT,A_DATE) VALUES('106','mayur','borivali','5500','21-dec-06');
SELECT * FROM DEPOSIT;

SELECT JOB_TITLE, MAX_SAL FROM JOB;

SELECT DISTINCT BNAME FROM DEPOSIT;

SELECT A_NO, AMOUNT FROM DEPOSIT WHERE A_DATE BETWEEN '01-JAN-06' and '25-SEP-06';

SELECT CNAME FROM DEPOSIT WHERE A_DATE>'09-OCT-06';

SELECT EMP_NAME AS "NAME", EMP_SAL FROM EMPLOYEE WHERE DEPT_NO=20;

SELECT EMP_NO, EMP_NAME, DEPT_NO FROM EMPLOYEE WHERE DEPT_NO IN (10,20);

SELECT EMP_NO, EMP_NAME, DEPT_NO FROM EMPLOYEE WHERE DEPT_NO NOT IN (15,30);

SELECT EMP_NO, EMP_NAME, DEPT_NO FROM EMPLOYEE WHERE DEPT_NO BETWEEN 15 AND 20;

SELECT * FROM EMPLOYEE WHERE EMP_COMM IS NOT NULL;

SELECT CONCAT(MIN_SAL, MAX_SAL) AS SALARY FROM JOB;


INSERT INTO SUPPLIER2 SELECT * FROM EMPLOYEE;
SELECT * FROM SUPPLIER2;

TRUNCATE TABLE SUP1;

SELECT * FROM SUP1;

INSERT INTO SUPPLIER(EMP_NO,EMP_NAME,EMP_SAL,EMP_COMM,DEPT_NO)VALUES('103','Adama','1100','425','20');
DELETE FROM SUPPLIER WHERE EMP_NO = 103; 
SELECT * FROM SUPPLIER;

UPDATE EMPLOYEE SET EMP_NAME = 'Aman' WHERE EMP_NAME = 'Anita';
SELECT * FROM EMPLOYEE;
    
UPDATE EMPLOYEE SET EMP_NAME = 'Nisarg' WHERE EMP_NO = 103;   

SELECT MAX(MAX_SAL) AS MAX_SALARY, MIN(MIN_SAL) AS MIN_SALARY FROM JOB;

