CREATE TABLE PRODUCT (
    DETORDER VARCHAR(30) NOT NULL ,
    PRODUCT_NO VARCHAR (30) NOT NULL ,
    QTY_ORDER NUMBER NOT NULL CHECK (QTY_ORDER > 0 )
);

CREATE TABLE EMP_COMPANY (
    ENAME VARCHAR(30) NOT NULL ,
    CNAME VARCHAR(30) NOT NULL ,
    SALARY NUMBER NOT NULL CHECK (SALARY >0 )
);

DESC PRODUCT ;
DESC EMP_COMPANY ;

INSERT INTO PRODUCT (Detorder, Product_no, Qty_order)
VALUES ('O19001', 'P00001', 10);
INSERT INTO PRODUCT (Detorder, Product_no, Qty_order)
VALUES ('O19001', 'P00002', 3);
INSERT INTO PRODUCT (Detorder, Product_no, Qty_order)
VALUES ('O19002', 'P00001', 4);
INSERT INTO PRODUCT (Detorder, Product_no, Qty_order)
VALUES ('O19003', 'P00004', 2);
INSERT INTO PRODUCT (Detorder, Product_no, Qty_order)
VALUES ('O19004', 'P00003', 6);
INSERT INTO PRODUCT (Detorder, Product_no, Qty_order)
VALUES ('O19005', 'P00005', 2);
INSERT INTO PRODUCT (Detorder, Product_no, Qty_order)
VALUES ('O19006', 'P00004', 7);

SELECT * FROM PRODUCT ;

INSERT INTO EMP_COMPANY (ENAME, CNAME, SALARY)
VALUES ('Anil', 'ACC', 1500);
INSERT INTO EMP_COMPANY (ENAME, CNAME, SALARY)
VALUES ('Shankar', 'TATA', 2000);
INSERT INTO EMP_COMPANY (ENAME, CNAME, SALARY)
VALUES ('Jay', 'WIPRO', 1800);
INSERT INTO EMP_COMPANY (ENAME, CNAME, SALARY)
VALUES ('Sunil', 'WIPRO', 1700);
INSERT INTO EMP_COMPANY (ENAME, CNAME, SALARY)
VALUES ('Vijay', 'TATA', 5000);
INSERT INTO EMP_COMPANY (ENAME, CNAME, SALARY)
VALUES ('Prakash', 'TATA', 3000);
INSERT INTO EMP_COMPANY (ENAME, CNAME, SALARY)
VALUES ('Ajay', 'ACC', 8000);
INSERT INTO EMP_COMPANY (ENAME, CNAME, SALARY)
VALUES ('Abhay', 'ACC', 1800);

SELECT * FROM EMP_COMPANY ;


SELECT PRODUCT_NO ,SUM(QTY_ORDER) AS TOTAL_ORDER FROM PRODUCT GROUP BY PRODUCT_NO ;

SELECT PRODUCT_NO ,SUM(QTY_ORDER) AS TOTAL_ORDER FROM PRODUCT GROUP BY PRODUCT_NO HAVING PRODUCT_NO='P00001' OR PRODUCT_NO='P00004' ;

SELECT CNAME , MAX(SALARY) AS MAXIMUM_SALARY FROM EMP_COMPANY GROUP BY CNAME ;

SELECT CNAME , AVG(SALARY) AS AVERAGE_SALARY FROM EMP_COMPANY GROUP BY CNAME ;

SELECT CNAME , AVG(SALARY) AS AVERAGE_SALARY FROM EMP_COMPANY GROUP BY CNAME HAVING AVG(SALARY) > 1500 ;

SELECT CNAME , AVG(SALARY) AS AVERAGE_SALARY FROM EMP_COMPANY GROUP BY CNAME HAVING CNAME NOT IN('ACC');