CREATE TABLE sup1 AS SELECT EMP_NAME,EMP_NO FROM employee WHERE 1=0 ;

CREATE TABLE sup2 AS SELECT * FROM employee ;


RENAME sup2 TO  supplier_2 ;

SELECT * FROM  employee ;



DROP TABLE sup1;
DROP TABLE sup2;


SELECT * FROM supplier_2 ;


ALTER TABLE supplier_2 DROP COLUMN EMP_NAME ;

ALTER TABLE supplier_2 RENAME COLUMN emp_sal TO new_sal ;

--pRACTICAL 3 

SELECT * FROM EMPLOYEE;
SELECT * FROM BORROW ;
SELECT * FROM DEPOSIT ;

SELECT * FROM JOB ;

SELECT JOB_TITLE,MAX_SAL FROM JOB ;

SELECT BNAME FROM DEPOSIT ;

SELECT A_NO,AMOUNT FROM DEPOSIT WHERE a_date BETWEEN '01-JAN-06' AND '25-JULY-06' ;

SELECT CNAME FROM DEPOSIT WHERE a_date> '09-OCT-06' ;

SELECT EMP_NAME AS "name" , emp_sal FROM EMPLOYEE WHERE DEPT_NO=20 ;

SELECT EMP_NO,EMP_NAME ,DEPT_NO FROM EMPLOYEE WHERE DEPT_NO in(10 ,20) ;

SELECT EMP_NAME FROM EMPLOYEE WHERE EMP_COMM IS NOT NULL ;

SELECT CONCAT (MIN_SAL , MAX_SAL) AS SALARY FROM JOB ;

SELECT COUNT (EMP_NO) AS "COUNT" FROM EMPLOYEE WHERE EMP_SAL>1000 ;



SELECT EMP_NO , EMP_NAME FROM EMPLOYEE ORDER BY EMP_ID ASC ;

SELECT * FROM EMPLOYEE;

SELECT EMP_COMM,EMP_SAL FROM EMPLOYEE ORDER BY EMP_COMM ASC ;